greetings-api:
  image: aatarasoff/greetings-api
  ports:
    - "8080"
  environment:
    SERVICE_NAME: greetings

consul-standalone:
  image: gliderlabs/consul-server
  container_name: consul
  ports:
    - "8500:8500"
    - "8400:8400"
    - "53:53/udp"
  restart: always
  net: "host"
  command: -bootstrap -ui-dir /ui

registrator:
  image: gliderlabs/registrator
  container_name: registrator
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  net: "host"
  restart: "always"
  links:
    - consul-standalone
  command: consul://
